import type { MenuCategory } from '@/types/menu';

export const MENU_CATEGORIES: MenuCategory[] = [
  {
    id: 'voorgerechten',
    slug: 'voorgerechten',
    title: 'Voorgerechten',
    titleEn: 'Starters & Appetizers',
    subtitle: 'Krokante traditionele deeghapjes en gekruide beignets om uw diner mee te openen',
    subtitleEn: 'Crispy traditional pastries and spiced fritters to begin your communal feast',
    items: [
      {
        id: 'samosa-veggie',
        name: 'Vegetarische Samosa',
        nameEn: 'Vegetarian Samosa',
        serving: 'per 3 stuks',
        servingEn: 'per 3 pieces',
        price: '€ 7,50',
        priceNumeric: 7.5,
        description: 'Krokante bladerdeegdriehoekjes gevuld met zacht gegaarde, gekruide linzen, zoete uien en milde specerijen.',
        descriptionEn: 'Crisp pastry triangles filled with slow-cooked spiced lentils, sweet onions, and mild Ethiopian herbs.',
        dietary: ['vegan', 'vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'samosa-beef',
        name: 'Samosa met Rundergehakt',
        nameEn: 'Beef Samosa',
        serving: 'per 3 stuks',
        servingEn: 'per 3 pieces',
        price: '€ 7,50',
        priceNumeric: 7.5,
        description: 'Goudbruine knapperige gebakjes rijk gevuld met fijn rundergehakt, knoflook, gember en Ethiopische specerijen.',
        descriptionEn: 'Golden-brown pastries richly filled with savory minced beef, garlic, ginger, and aromatic highland spices.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'veggie-beignets',
        name: 'Vegetarische Beignets',
        nameEn: 'Vegetable Beignets',
        serving: 'per 5 stuks',
        servingEn: 'per 5 pieces',
        price: '€ 7,50',
        priceNumeric: 7.5,
        description: 'Traditioneel gekruide groentebeignets, goudgeel en krokant gebakken, vergezeld van een pittige awaze-dipsaus.',
        descriptionEn: 'Traditionally seasoned vegetable fritters, fried golden and crisp, served with our house-made spicy awaze dip.',
        dietary: ['vegan', 'vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
  {
    id: 'vleesgerechten',
    slug: 'vleesgerechten',
    title: 'Hoofdgerechten Vlees',
    titleEn: 'Traditional Meat Specialties',
    subtitle: 'Langzaam gestoofd rundvlees en malse kip met berbere en kruidenboter. Geserveerd met verse injera en salade.',
    subtitleEn: 'Slow-simmered prime beef and tender chicken in berbere spices and niter kibbeh. Served with fresh teff injera.',
    items: [
      {
        id: 'doro-wot',
        name: 'Doro Wot (Doro Woti)',
        nameEn: 'Doro Wot (Celebration Chicken Stew)',
        price: '€ 24,00',
        priceNumeric: 24.0,
        description: 'Gestoofde kip met verschillende kruiden. Rijke in roodgekleurde saus gestoofde kip; de schotel krijgt zijn dieprode gloed van berbere. Geserveerd met verse kaas en een ei.',
        descriptionEn: 'Ethiopia’s revered national dish: chicken drumsticks simmered in deeply aromatic berbere sauce with spiced butter, served with a hard-boiled egg and fresh ayib cheese.',
        dietary: ['spicy'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'gele-tibs',
        name: 'Gele Tibs',
        nameEn: 'Gele Tibs (Mild Sautéed Beef)',
        price: '€ 24,00',
        priceNumeric: 24.0,
        description: 'Gegrild rundvlees gekruid met knoflook, zwarte peper, ui, groene pepers met mitmita saus.',
        descriptionEn: 'Grilled beef flash-sautéed with garlic, black pepper, sliced onions, and fresh jalapeños, served with spicy mitmita dipping powder.',
        dietary: ['spicy'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'awaze-tibs',
        name: 'Awaze Tibs',
        nameEn: 'Awaze Tibs (Spicy Sautéed Beef)',
        price: '€ 22,00',
        priceNumeric: 22.0,
        description: 'Rundvlees gemarineerd met speciale kruiden, knoflook, ui en groene chilipeper; gebracht op een warm bord.',
        descriptionEn: 'Tender cubes of beef marinated in house-made spicy awaze chili paste, flash-seared with garlic, red onions, and rosemary.',
        dietary: ['spicy'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'kitfo',
        name: 'Kitfo (Kifto)',
        nameEn: 'Kitfo (Steak Tartare Speciality)',
        price: '€ 22,00',
        priceNumeric: 22.0,
        description: 'Vers mager gemalen rundvlees gemarineerd met pikante boter, chilipeper, Ethiopische kaas en Ethiopische boerenkool.',
        descriptionEn: 'Prime lean minced beef seasoned with warmed herbal butter (niter kibbeh) and fiery mitmita. Served with mild ayib cheese and collard greens.',
        dietary: ['spicy'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'key-wot',
        name: 'Key Wot',
        nameEn: 'Key Wot (Spicy Beef Stew)',
        price: '€ 20,00',
        priceNumeric: 20.0,
        description: 'Hete pittige runderstoofpot gekookt met perfectie; wordt geleverd in een traditionele kleipot.',
        descriptionEn: 'Spicy, rich beef stew slow-cooked to fork-tender perfection in aromatic berbere. Served in an authentic earthenware pot.',
        dietary: ['spicy'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'gomen-besiga',
        name: 'Gomen Besiga',
        nameEn: 'Gomen Besiga (Beef & Collards)',
        price: '€ 20,00',
        priceNumeric: 20.0,
        description: 'Rundvleesblokjes, boerenkool en uien zachtjes gekookt in boter met een vleugje kardemom.',
        descriptionEn: 'Tender beef cubes gently braised with fresh collard greens, onions, and spiced butter with fragrant cardamom notes.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
  {
    id: 'vegetarisch-vegan',
    slug: 'vega',
    title: 'Hoofdgerechten Vega & Vegan (Yetsom)',
    titleEn: 'Vegetarian & Vegan Specialties (Yetsom)',
    subtitle: 'Puur plantaardige stoofgerechten rijk aan smaak volgens de Ethiopische vastentraditie. Geserveerd met verse injera.',
    subtitleEn: 'Wholly plant-based stews steeped in ancient fasting traditions. Served with fresh handcrafted injera.',
    items: [
      {
        id: 'shiro-wot',
        name: 'Shiro Wot',
        nameEn: 'Shiro Wot (Chickpea Stew)',
        price: '€ 20,00',
        priceNumeric: 20.0,
        description: 'Pittige shiro (kikkererwtenmeel) stoofpot bereid op traditionele wijze. Geserveerd in een authentieke kleipot.',
        descriptionEn: 'Velvety, spiced powdered chickpea stew slow-simmered with garlic, onions, and herbs. Served in a traditional clay pot.',
        dietary: ['vegan', 'vegetarian'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'misir-wot',
        name: 'Misir Wot',
        nameEn: 'Misir Wot (Red Lentil Stew)',
        price: '€ 20,00',
        priceNumeric: 20.0,
        description: 'Licht gepureerde linzen en gele spliterwten gesudderd in een milde aromatische saus van ui, curry en specerijen.',
        descriptionEn: 'Pureed red lentils and split peas simmered gently in an aromatic berbere, onion, and garlic reduction.',
        dietary: ['vegan', 'vegetarian', 'spicy'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'tikil-gomen',
        name: 'Tikil Gomen',
        nameEn: 'Tikil Gomen (Cabbage & Carrots)',
        price: '€ 20,00',
        priceNumeric: 20.0,
        description: 'Fijngesneden malse kool, wortelen en aardappelblokjes, gekookt tot perfectie in een milde, zachte saus.',
        descriptionEn: 'Tender sliced cabbage, sweet carrots, and potato chunks braised in a fragrant, golden turmeric and ginger broth.',
        dietary: ['vegan', 'vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'gomen',
        name: 'Gomen',
        nameEn: 'Gomen (Simmered Greens)',
        price: '€ 20,00',
        priceNumeric: 20.0,
        description: 'Verse boerenkool zachtjes gestoofd met knoflook, ui en aromatische specerijen.',
        descriptionEn: 'Fresh collard greens slow-cooked with fresh garlic, red onions, and delicate Ethiopian highland seasonings.',
        dietary: ['vegan', 'vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
  {
    id: 'combinatieschotels',
    slug: 'combinaties',
    title: 'Combinatieschotels (Voor 2 Personen)',
    titleEn: 'Communal Combination Feasts (for 2)',
    subtitle: 'Gezamenlijk genieten van een rijke proeverij, geserveerd op een grote centrale injera aan het Mesob',
    subtitleEn: 'A magnificent shared tasting platter arranged atop fresh injera around the communal Mesob basket',
    items: [
      {
        id: 'taste-special-2p',
        name: 'Taste of Ethiopia Special',
        nameEn: 'Taste of Ethiopia Grand Feast',
        serving: '2 personen',
        servingEn: '2 guests',
        price: '€ 40,00',
        priceNumeric: 40.0,
        description: 'Een royale mix van alle vlees- en vegetarische gerechten op onze menukaart, rijkelijk gepresenteerd op een grote gedeelde injera.',
        descriptionEn: 'Our ultimate banquet: a generous assortment of all tender meat stews and vibrant vegetarian dishes, served on a shared central injera.',
        dietary: [],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'veggie-combo-2p',
        name: 'Veggie Combo',
        nameEn: 'Veggie Feast (Yetsom Beyaynetu)',
        serving: '2 personen',
        servingEn: '2 guests',
        price: '€ 35,00',
        priceNumeric: 35.0,
        description: 'Onze beste groentecombinatie: rode linzen, gele spliterwten, boerenkool, kool en een combinatie van erwten- en linzensauzen.',
        descriptionEn: 'Our premier vegan array: spicy red lentils (Misir Wot), yellow split peas, braised greens (Gomen), cabbage (Tikil Gomen), and creamy Shiro.',
        dietary: ['vegan', 'vegetarian'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
  {
    id: 'desserts',
    slug: 'desserts',
    title: 'Desserts & Ambachtelijk IJs',
    titleEn: 'Desserts & Artisan Ice Cream',
    subtitle: 'Verfijnde zoete lekkernijen en ambachtelijk schepijs om uw maaltijd compleet te maken',
    subtitleEn: 'Delicate sweet treats and artisanal gelato to conclude your dining experience',
    items: [
      {
        id: 'chocolade-taart',
        name: 'Chocolade Taart',
        nameEn: 'Rich Chocolate Cake',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Rijke, smeuïge chocoladetaart met diepe cacaotonen.',
        descriptionEn: 'Rich, moist chocolate cake with deep cocoa notes.',
        dietary: ['vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'redvelvet-cake',
        name: 'Red Velvet Cake',
        nameEn: 'Red Velvet Cake',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Klassieke fluweelzachte taart met een romige vanille-frosting.',
        descriptionEn: 'Classic velvety cake topped with smooth cream cheese frosting.',
        dietary: ['vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'raffaello-cake',
        name: 'Raffaello Cake',
        nameEn: 'Raffaello Cake',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Luchtige taart met witte chocolade, fijne kokos en amandelaccenten.',
        descriptionEn: 'Airy sponge cake infused with white chocolate, fine coconut, and almond.',
        dietary: ['vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'pistache-cake',
        name: 'Pistache Cake',
        nameEn: 'Pistachio Cake',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Ambachtelijke taart bereid met geurige gemalen pistachenoten.',
        descriptionEn: 'Artisan cake prepared with finely ground aromatic pistachios.',
        dietary: ['vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'ijs-glas',
        name: 'Ambachtelijk IJs in een Glas',
        nameEn: 'Artisan Ice Cream in Glass',
        serving: '3 schepjes',
        servingEn: '3 scoops',
        price: '€ 7,50',
        priceNumeric: 7.5,
        description: 'Drie bollen ijs geserveerd in een glas. Smaken: vanille, aardbei, citroen, zwarte sesam, mokka, chocolade, groene thee of pistache.',
        descriptionEn: 'Three scoops of gelato in a chilled glass. Flavors: vanilla, strawberry, lemon, black sesame, mocha, chocolate, green tea, or pistachio.',
        dietary: ['vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'ijs-koekjescoupe',
        name: 'Ambachtelijk IJs in een Koekjescoupe',
        nameEn: 'Artisan Ice Cream in Waffle Coupe',
        serving: '3 schepjes',
        servingEn: '3 scoops',
        price: '€ 7,50',
        priceNumeric: 7.5,
        description: 'Drie bollen ijs geserveerd in een knapperige wafelcoupe. Smaken: vanille, aardbei, citroen, zwarte sesam, mokka, chocolade, groene thee of pistache.',
        descriptionEn: 'Three scoops of gelato in a crisp artisan waffle bowl. Flavors: vanilla, strawberry, lemon, black sesame, mocha, chocolate, green tea, or pistachio.',
        dietary: ['vegetarian'],
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
  {
    id: 'ethiopische-bieren',
    slug: 'bieren',
    title: 'Ethiopische Bieren, Koffieceremonie & Bier',
    titleEn: 'Ethiopian Beers, Bunna & Brews',
    subtitle: 'Exclusief geïmporteerde hooglandbieren en traditionele dranken',
    subtitleEn: 'Directly imported highland lagers and ancient celebratory drinks',
    items: [
      {
        id: 'bunna-ceremony',
        name: 'Traditionele Koffieceremonie (Bunna)',
        nameEn: 'Traditional Coffee Ceremony (Bunna)',
        price: '€ 5,50',
        priceNumeric: 5.5,
        description: 'Vers gebrande Ethiopische bonen zacht gebrouwen in de traditionele aardewerken Jebena, vergezeld van wierook en verse popcorn.',
        descriptionEn: 'Freshly roasted Arabica beans brewed in the clay Jebena pot, accompanied by frankincense and popped corn.',
        dietary: ['vegan'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'st-george',
        name: 'St. George Pilsener',
        nameEn: 'St. George Pilsener (Ethiopia)',
        serving: 'Ethiopisch bier',
        servingEn: 'Ethiopian beer',
        price: '€ 4,00',
        priceNumeric: 4.0,
        description: 'Ethiopië’s meest iconische pilsener. Gebrouwen uit geselecteerde mout, verfijnde hop en natuurlijk hooglandwater.',
        descriptionEn: 'Ethiopia’s iconic lager, brewed with selected barley malt, refined hops, and purified highland spring water.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'walia-beer',
        name: 'Walia Pilsener',
        nameEn: 'Walia Pilsener (Ethiopia)',
        serving: 'Ethiopisch bier',
        servingEn: 'Ethiopian beer',
        price: '€ 4,00',
        priceNumeric: 4.0,
        description: 'Licht en evenwichtig lager bier uit Ethiopië, gebrouwen met 100% zuivere gerstemout.',
        descriptionEn: 'Crisp, smooth Ethiopian lager brewed with 100% pure malted barley.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'bedele-beer',
        name: 'Bedele Pilsener (5.5%)',
        nameEn: 'Bedele Special Export (5.5%)',
        serving: 'Ethiopisch bier',
        servingEn: 'Ethiopian beer',
        price: '€ 4,00',
        priceNumeric: 4.0,
        description: 'Rijk en volmondig export pilsener gebrouwen met twee types hop en zuiver natuurlijke ingrediënten.',
        descriptionEn: 'Full-bodied export-strength lager brewed with two distinct hops and all-natural ingredients.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'habesha-beer',
        name: 'Habesha Pilsener',
        nameEn: 'Habesha Cold Gold',
        serving: 'Ethiopisch bier',
        servingEn: 'Ethiopian beer',
        price: '€ 4,00',
        priceNumeric: 4.0,
        description: 'Koud gebrouwen goudblond pilsener met natuurlijk mineraalwater, gerstemout, tarwe en hop.',
        descriptionEn: 'Cold-brewed golden lager crafted from pure mineral water, barley malt, wheat, and hops.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'hertog-jan-beer',
        name: 'Hertog Jan Pilsener',
        nameEn: 'Hertog Jan Pilsener',
        serving: 'Nederlands bier',
        servingEn: 'Dutch beer',
        price: '€ 4,00',
        priceNumeric: 4.0,
        description: 'Traditioneel Nederlands pilsener met een karaktervolle, moutige afdronk.',
        descriptionEn: 'Classic Dutch pilsener with a rich, malt-forward character.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'heineken-beer',
        name: 'Heineken Pilsener',
        nameEn: 'Heineken Lager',
        serving: 'Nederlands bier',
        servingEn: 'Dutch beer',
        price: '€ 4,00',
        priceNumeric: 4.0,
        description: 'Verfrissend en helder Nederlands lager bier.',
        descriptionEn: 'Crisp, world-famous Dutch lager.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
  {
    id: 'wijnen',
    slug: 'wijnen',
    title: 'Wijnen & Traditionele Tej',
    titleEn: 'Wines & Ancient Honey Wine (Tej)',
    subtitle: 'Rift Valley wijnen uit Ethiopië, traditionele honingwijn en geselecteerde wereldwijnen (fles)',
    subtitleEn: 'Ethiopian Rift Valley estate wines, ancient honey wine, and curated cellar bottles',
    items: [
      {
        id: 'tej-honeywine',
        name: 'Tej Honingwijn (in traditioneel glas / fles)',
        nameEn: 'Tej Honey Wine (Traditional Berele Glass / Bottle)',
        serving: 'Fles / traditioneel berele glas',
        servingEn: 'Bottle / traditional round berele',
        price: '€ 30,00',
        priceNumeric: 30.0,
        description: 'De legendarische Ethiopische zoete gouden honingwijn met verfijnde florale aroma’s en een hint van perzik en abrikoos.',
        descriptionEn: 'Legendary golden Ethiopian honey wine, fermented with gesho hops, featuring lush aromas of wild honey and peach.',
        dietary: ['vegetarian'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'rift-valley-merlot',
        name: 'Rift Valley Merlot (Ethiopië)',
        nameEn: 'Rift Valley Merlot (Ethiopia)',
        serving: 'Droog rood',
        servingEn: 'Dry red',
        price: '€ 35,00',
        priceNumeric: 35.0,
        description: 'Volle robijnrode wijn uit de Ethiopische Rift Valley met een rond gehemelte en subtiele tonen van donker geroosterde koffie.',
        descriptionEn: 'Full-bodied ruby red from Ethiopia’s Rift Valley with rounded tannins and subtle hints of dark roasted coffee.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'rift-valley-cabernet',
        name: 'Rift Valley Cabernet Sauvignon (Ethiopië)',
        nameEn: 'Rift Valley Cabernet Sauvignon (Ethiopia)',
        serving: 'Droog rood',
        servingEn: 'Dry red',
        price: '€ 35,00',
        priceNumeric: 35.0,
        description: 'Briljante dieprode kleur, intense aroma’s van groene paprika en specerijen met een soepele, evenwichtige body.',
        descriptionEn: 'Deep crimson hue with intense notes of green pepper, savory spice, and a balanced, supple body.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'rift-valley-syrah',
        name: 'Rift Valley Syrah (Ethiopië)',
        nameEn: 'Rift Valley Syrah (Ethiopia)',
        serving: 'Droog rood',
        servingEn: 'Dry red',
        price: '€ 35,00',
        priceNumeric: 35.0,
        description: 'Volle robijnrode wijn met fluweelzachte tannines en warme tonen van rijp donker fruit.',
        descriptionEn: 'Lush and powerful red featuring velvety tannins and warm dark berry notes.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'rift-valley-chardonnay',
        name: 'Rift Valley Chardonnay (Ethiopië)',
        nameEn: 'Rift Valley Chardonnay (Ethiopia)',
        serving: 'Droog wit',
        servingEn: 'Dry white',
        price: '€ 35,00',
        priceNumeric: 35.0,
        description: 'Verfrissende aroma’s van perzik en abrikoos met een zachte toets van hooglandhoning.',
        descriptionEn: 'Refreshing peach and stone fruit aromas balanced by a soft touch of wild honey.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'franse-merlot',
        name: 'Franse Merlot',
        nameEn: 'French Merlot',
        serving: 'Rode wijn',
        servingEn: 'Red wine',
        price: '€ 35,00',
        priceNumeric: 35.0,
        description: 'Soepel, roodfruitig en zacht met uitgesproken aroma’s van zwarte bessen.',
        descriptionEn: 'Supple, fruit-forward red wine bursting with blackcurrant aromas.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'franse-tradition',
        name: 'Franse Tradition',
        nameEn: 'French Tradition',
        serving: 'Rode wijn',
        servingEn: 'Red wine',
        price: '€ 35,00',
        priceNumeric: 35.0,
        description: 'Karaktervolle Franse wijn met tonen van cassis, subtiele kruidigheid en een zachte finale.',
        descriptionEn: 'Characterful French blend with cassis notes, subtle spice, and a velvety finish.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'us-moscato',
        name: 'Amerikaanse Moscato',
        nameEn: 'Californian Moscato',
        serving: 'Zoet wit',
        servingEn: 'Sweet white',
        price: '€ 30,00',
        priceNumeric: 30.0,
        description: 'Zoete en fruitige witte wijn met tonen van ananas, perzik en oranjebloesem.',
        descriptionEn: 'Sweet and luscious white wine with pineapple, peach, and orange blossom notes.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'us-sauvignon-blanc',
        name: 'Amerikaanse Sauvignon Blanc',
        nameEn: 'Californian Sauvignon Blanc',
        serving: 'Droog wit',
        servingEn: 'Dry white',
        price: '€ 30,00',
        priceNumeric: 30.0,
        description: 'Frisse en florale witte wijn met tonen van groene appel, perzik en een vleugje citrus.',
        descriptionEn: 'Crisp white wine with notes of green apple, white peach, and zesty citrus.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'us-pinot-grigio',
        name: 'Amerikaanse Pinot Grigio',
        nameEn: 'Californian Pinot Grigio',
        serving: 'Droog wit',
        servingEn: 'Dry white',
        price: '€ 30,00',
        priceNumeric: 30.0,
        description: 'Frisse, fruitige witte wijn met nuances van meloen en citrusvruchten.',
        descriptionEn: 'Light, crisp wine with melon notes and clean mineral acidity.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'us-chardonnay',
        name: 'Amerikaanse Chardonnay',
        nameEn: 'Californian Chardonnay',
        serving: 'Droog wit',
        servingEn: 'Dry white',
        price: '€ 30,00',
        priceNumeric: 30.0,
        description: 'Rijke witte wijn met tonen van perzik, zachte vanille en een vleugje honing.',
        descriptionEn: 'Round white wine showcasing ripe peach, light vanilla oak, and honey.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'us-white-zinfandel',
        name: 'Amerikaanse White Zinfandel',
        nameEn: 'Californian White Zinfandel',
        serving: 'Rosé',
        servingEn: 'Rosé',
        price: '€ 30,00',
        priceNumeric: 30.0,
        description: 'Prachtige fruitige rosé met levendige smaken van rijpe kersen en frambozen.',
        descriptionEn: 'Vibrant, easy-drinking rosé with sweet strawberry and raspberry flavors.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'us-merlot',
        name: 'Amerikaanse Merlot',
        nameEn: 'Californian Merlot',
        serving: 'Rode wijn',
        servingEn: 'Red wine',
        price: '€ 30,00',
        priceNumeric: 30.0,
        description: 'Soepele en aromatische rode wijn met aroma’s van rijpe bosvruchten en frambozen.',
        descriptionEn: 'Smooth, aromatic red with ripe plum, wild berry, and cocoa nuances.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
  {
    id: 'smoothies-frisdrank',
    slug: 'smoothies',
    title: 'Verse Smoothies, Shakes & Frisdranken',
    titleEn: 'Fresh Smoothies, Shakes & Soft Drinks',
    subtitle: 'Puur vers fruit, huisgemaakte shakes en verfrissende koude dranken',
    subtitleEn: 'Fresh tropical fruit smoothies, cold milkshakes, and soft drinks',
    items: [
      {
        id: 'smoothie-papaya',
        name: 'Verse Papaya Smoothie',
        nameEn: 'Fresh Papaya Smoothie',
        price: '€ 7,00',
        priceNumeric: 7.0,
        description: 'Vers gemixte zongerijpte papaya, rijk en romig.',
        descriptionEn: 'Freshly blended sun-ripened tropical papaya, rich and creamy.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'smoothie-avocado',
        name: 'Verse Avocado Smoothie',
        nameEn: 'Fresh Avocado Smoothie',
        price: '€ 6,50',
        priceNumeric: 6.5,
        description: 'Traditionele Ethiopische favoriet: romige verse avocado met een fris vleugje limoen.',
        descriptionEn: 'Ethiopian classic: rich blended ripe avocado touched with fresh lime.',
        dietary: ['vegan'],
        isSignature: true,
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'smoothie-aardbei',
        name: 'Verse Aardbei Smoothie',
        nameEn: 'Fresh Strawberry Smoothie',
        price: '€ 6,50',
        priceNumeric: 6.5,
        description: 'Frisse en zoete smoothie van verse aardbeien.',
        descriptionEn: 'Sweet and refreshing smoothie of pure strawberries.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'smoothie-mango',
        name: 'Verse Mango Smoothie',
        nameEn: 'Fresh Mango Smoothie',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Romige smoothie van rijpe zoete mango.',
        descriptionEn: 'Creamy smoothie prepared from ripe tropical mangoes.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'smoothie-banaan',
        name: 'Verse Banaan Smoothie',
        nameEn: 'Fresh Banana Smoothie',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Volle smoothie van verse bananen.',
        descriptionEn: 'Wholesome, naturally sweet fresh banana smoothie.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'smoothie-kiwi',
        name: 'Verse Kiwi Smoothie',
        nameEn: 'Fresh Kiwi Smoothie',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Verfrissende smoothie van verse groene kiwi.',
        descriptionEn: 'Zesty and vitamin-packed pure green kiwi blend.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'fruitshake-aardbei',
        name: 'Fruit Shake Aardbei',
        nameEn: 'Strawberry Fruit Shake',
        price: '€ 6,25',
        priceNumeric: 6.25,
        description: 'Koude fruitshake van gepureerde aardbeien met crushed ijs.',
        descriptionEn: 'Chilled fruit shake made with pureed strawberries and crushed ice.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'fruitshake-mango',
        name: 'Fruit Shake Mango',
        nameEn: 'Mango Fruit Shake',
        price: '€ 6,25',
        priceNumeric: 6.25,
        description: 'Heerlijke gekoelde fruitshake van rijpe mango.',
        descriptionEn: 'Refreshing cold shake prepared from ripe mango puree.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'fruitshake-avocado',
        name: 'Fruit Shake Avocado',
        nameEn: 'Avocado Fruit Shake',
        price: '€ 6,25',
        priceNumeric: 6.25,
        description: 'Verkwikkende koude shake van verse avocado.',
        descriptionEn: 'Velvety cold shake prepared with fresh ripe avocado.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'fruitshake-banaan',
        name: 'Fruit Shake Banaan',
        nameEn: 'Banana Fruit Shake',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Zachte koude fruitshake van verse banaan.',
        descriptionEn: 'Smooth cold shake crafted with ripe bananas.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'coca-cola',
        name: 'Coca-Cola / Coca-Cola Zero',
        nameEn: 'Coca-Cola / Coca-Cola Zero',
        price: '€ 6,50',
        priceNumeric: 6.5,
        description: 'Klassieke gekoelde cola of suikervrije Zero.',
        descriptionEn: 'Chilled regular or sugar-free Zero cola.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'fanta',
        name: 'Fanta Orange / Cassis',
        nameEn: 'Fanta Orange / Cassis',
        price: '€ 6,00',
        priceNumeric: 6.0,
        description: 'Fruitige frisdrank orange of cassis.',
        descriptionEn: 'Sparkling orange or blackcurrant soda.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'red-bull',
        name: 'Red Bull Energy Drink',
        nameEn: 'Red Bull Energy Drink',
        price: '€ 3,50',
        priceNumeric: 3.5,
        description: 'Gekoeld blikje energiedrank.',
        descriptionEn: 'Chilled can of energy drink.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'sprite',
        name: 'Sprite',
        nameEn: 'Sprite',
        price: '€ 3,00',
        priceNumeric: 3.0,
        description: 'Verfrissende sprankelende citroen-limoen frisdrank.',
        descriptionEn: 'Crisp lemon-lime sparkling soda.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'lipton-icetea',
        name: 'Lipton Ice Tea (Green / Sparkling / Sparkling Peach)',
        nameEn: 'Lipton Ice Tea (Green / Sparkling / Peach)',
        price: '€ 3,00',
        priceNumeric: 3.0,
        description: 'Verfrissende ijsthee naar keuze.',
        descriptionEn: 'Refreshing iced tea in green, sparkling, or peach.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'finley',
        name: 'Finley (Bitter Lemon / Ginger Ale / Tonic)',
        nameEn: 'Finley (Bitter Lemon / Ginger Ale / Tonic)',
        price: '€ 3,00',
        priceNumeric: 3.0,
        description: 'Karaktervolle frisdrank met fijne bubbel.',
        descriptionEn: 'Sparkling adult mixers: bitter lemon, ginger ale, or tonic.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'chaudfontaine',
        name: 'Chaudfontaine Mineraalwater (Stil / Bruisend)',
        nameEn: 'Chaudfontaine Mineral Water (Still / Sparkling)',
        price: '€ 3,00',
        priceNumeric: 3.0,
        description: 'Zuiver mineraalwater stil (blauw) of sprankelend (rood).',
        descriptionEn: 'Pure mineral water in still (blue) or sparkling (red).',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
  {
    id: 'cocktails-spirits',
    slug: 'cocktails',
    title: 'Cocktails, Mocktails & Gedistilleerd',
    titleEn: 'Cocktails, Mocktails & Fine Spirits',
    subtitle: 'Klassieke cocktails, verfrissende alcoholvrije mocktails en zorgvuldig geselecteerde dranken',
    subtitleEn: 'Classic cocktails, refreshing zero-proof mocktails, and curated spirits',
    items: [
      {
        id: 'long-island',
        name: 'Long Island Ice Tea',
        nameEn: 'Long Island Iced Tea',
        price: '€ 9,50',
        priceNumeric: 9.5,
        description: 'Citroensap, gin, triple sec, witte rum, wodka en tequila met een scheutje cola.',
        descriptionEn: 'Fresh lemon juice, gin, triple sec, white rum, vodka, and tequila with a splash of cola.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'pina-colada',
        name: 'Piña Colada',
        nameEn: 'Piña Colada',
        price: '€ 8,50',
        priceNumeric: 8.5,
        description: 'Ananassap en zachte kokosroom geshaket met Caribische witte rum.',
        descriptionEn: 'Pineapple juice and rich coconut cream shaken with Caribbean white rum.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'espresso-martini',
        name: 'Espresso Martini',
        nameEn: 'Espresso Martini',
        price: '€ 8,50',
        priceNumeric: 8.5,
        description: 'Verse espresso, premium koffielikeur en wodka met een fluweelzachte crèmelaag.',
        descriptionEn: 'Fresh espresso, premium coffee liqueur, and vodka crowned with velvety crema.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'singapore-sling',
        name: 'Singapore Sling',
        nameEn: 'Singapore Sling',
        price: '€ 8,50',
        priceNumeric: 8.5,
        description: 'Ananassap, limoensap, bénédictine en cherry brandy met gin.',
        descriptionEn: 'Pineapple juice, lime juice, Bénédictine, and cherry brandy shaken with London dry gin.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'manhattan',
        name: 'Manhattan',
        nameEn: 'Manhattan',
        price: '€ 8,50',
        priceNumeric: 8.5,
        description: 'Bourbon whiskey met rode vermout en aromatische bitters.',
        descriptionEn: 'Bourbon whiskey stirred with sweet red vermouth and Angostura bitters.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'sidecar',
        name: 'Sidecar',
        nameEn: 'Sidecar',
        price: '€ 8,50',
        priceNumeric: 8.5,
        description: 'Franse cognac, triple sec en vers geperst citroensap.',
        descriptionEn: 'French cognac, triple sec, and freshly squeezed lemon juice.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'mojito',
        name: 'Mojito',
        nameEn: 'Mojito',
        price: '€ 8,50',
        priceNumeric: 8.5,
        description: 'Bacardi Carta Blanca, verse limoen, munt, rietsuiker met Red Bull of bruiswater.',
        descriptionEn: 'Bacardi Carta Blanca, fresh lime wedges, mint, cane sugar with Red Bull or club soda.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'nojito-mocktail',
        name: 'Nojito — Virgin Mojito (Alcoholvrij)',
        nameEn: 'Nojito — Virgin Mojito (Zero Alcohol)',
        price: '€ 6,50',
        priceNumeric: 6.5,
        description: 'Verse limoenpartjes, frisse munt, rietsuiker en ijskoude ginger ale.',
        descriptionEn: 'Fresh lime wedges, muddled mint, pure cane sugar, and chilled ginger ale.',
        dietary: ['vegan'],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'jw-blue-label',
        name: 'Johnnie Walker Blue Label',
        nameEn: 'Johnnie Walker Blue Label',
        serving: 'Whisky per glas',
        servingEn: 'Whisky per glass',
        price: '€ 25,00',
        priceNumeric: 25.0,
        description: 'Exclusieve Schotse blend met uitzonderlijk zachte en rijke tonen.',
        descriptionEn: 'Extraordinary Scotch blend characterized by velvet smoothness and deep honeyed fruit.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'whisky-selectie',
        name: 'Premium Schotse & Amerikaanse Whisky',
        nameEn: 'Premium Scotch & American Whiskies',
        serving: 'Green / Gold / Black / Double Black / Red / Jack Daniel’s / Dimple / Captain Morgan',
        servingEn: 'Green / Gold / Black / Double Black / Red / Jack Daniel’s / Dimple / Captain Morgan',
        price: '€ 6,00 – € 8,00',
        priceNumeric: 7.0,
        description: 'Johnnie Walker Green Label (€8), Gold Label (€8), Double Black (€7), Black Label (€7), Red Label (€6), Dimple Golden (€6), Jack Daniel’s (€6), Captain Morgan (€6).',
        descriptionEn: 'Johnnie Walker Green Label (€8), Gold Label (€8), Double Black (€7), Black Label (€7), Red Label (€6), Dimple Golden (€6), Jack Daniel’s (€6), Captain Morgan (€6).',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'cognac-selectie',
        name: 'Franse Cognac (Hennessy / Rémy Martin)',
        nameEn: 'French Cognac (Hennessy / Rémy Martin)',
        serving: 'Cognac per glas',
        servingEn: 'Cognac per glass',
        price: '€ 8,00',
        priceNumeric: 8.0,
        description: 'Elegante en gerijpte Franse cognac met tonen van eikenhout, vanille en gedroogd fruit.',
        descriptionEn: 'Aged French cognac displaying oak, vanilla, and dried orchard fruit notes.',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'vodka-selectie',
        name: 'Vodka Selectie (Grey Goose / Belvedere / Kilos / Three Sixty / Smirnoff)',
        nameEn: 'Fine Vodka Selection (Grey Goose / Belvedere / Kilos / Three Sixty / Smirnoff)',
        serving: 'Vodka per glas',
        servingEn: 'Vodka per glass',
        price: '€ 5,00 – € 8,00',
        priceNumeric: 6.0,
        description: 'Grey Goose (€8), Belvedere (€8), Dutch Vodka Kilos (€7), Three Sixty (€6), Smirnoff (€5), Esbjaerg (€5), Ursus (€5), Absolut Lemon (€5).',
        descriptionEn: 'Grey Goose (€8), Belvedere (€8), Dutch Vodka Kilos (€7), Three Sixty (€6), Smirnoff (€5), Esbjaerg (€5), Ursus (€5), Absolut Lemon (€5).',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
      {
        id: 'likeuren-shots',
        name: 'Likeuren & Shots (Licor 43 / Baileys / Safari / Malibu / Tequila / Jägermeister)',
        nameEn: 'Liqueurs & Shots (Licor 43 / Baileys / Safari / Malibu / Tequila / Jägermeister)',
        serving: 'Per glas / shot',
        servingEn: 'Per glass / shot',
        price: '€ 5,00 – € 6,00',
        priceNumeric: 5.0,
        description: 'Licor 43 (€5), Baileys (€5), Safari (€5), Martini (€5), Malibu (€5), Passoã (€5), Bacardi Bianca/Razz (€6), Tequila Rose (€5), Tequila Silver (€5), Sourz (€5), Jägermeister (€5).',
        descriptionEn: 'Licor 43 (€5), Baileys (€5), Safari (€5), Martini (€5), Malibu (€5), Passoã (€5), Bacardi Bianca/Razz (€6), Tequila Rose (€5), Tequila Silver (€5), Sourz (€5), Jägermeister (€5).',
        dietary: [],
        status: 'CLIENT_VERIFIED',
      },
    ],
  },
];
